services:
 - docker
before_install:
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL4000 --ignore DL3008 - < Dockerfile
install:
  - docker build -t grafana-alpine .
  - docker run -d -p 127.0.0.1:3000:3000 --name grafana-alpine grafana-alpine
script:
  - docker ps | grep -q grafana-alpine
